// Builds the page one folder up.
//
//   node build.mjs                  -> ../assets/show.js, ../assets/show.css, ../assets/earth/textures.js
//   node build.mjs --watch          same, rebuilding on change
//   node build.mjs --entry harness/earth.js --out harness/out/earth.js
//                                   bundles one harness page (used while building a module on its own)
//
// Everything the page needs ends up in ../assets, so the folder works when opened
// straight from disk (file://) as well as from a web host.

import * as esbuild from 'esbuild';
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, readdirSync, mkdirSync, statSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const assets = resolve(here, '..', 'assets');
const args = process.argv.slice(2);
const flag = (name) => {
  const i = args.indexOf(name);
  return i === -1 ? null : (args[i + 1] ?? true);
};

const common = {
  bundle: true,
  target: ['es2020', 'safari15', 'chrome90', 'firefox90'],
  legalComments: 'none',
  logLevel: 'warning',
};

// one entry, for a harness page (.js or .css)
if (flag('--entry')) {
  const entry = resolve(here, flag('--entry'));
  const isCss = entry.endsWith('.css');
  const out = resolve(here, flag('--out') || join('harness', 'out', isCss ? 'bundle.css' : 'bundle.js'));
  mkdirSync(dirname(out), { recursive: true });
  await esbuild.build(
    isCss
      ? { ...common, entryPoints: [entry], outfile: out, loader: { '.woff2': 'dataurl' } }
      : { ...common, entryPoints: [entry], outfile: out, format: 'iife', sourcemap: 'inline', minify: false },
  );
  console.log('built', out);
  process.exit(0);
}

// Earth textures as data: URIs, for file:// where WebGL refuses to read local images
function writeTextureScript() {
  const dir = join(assets, 'earth');
  const names = readdirSync(dir).filter((f) => f.endsWith('.jpg')).sort();
  const parts = names.map((f) => {
    const b64 = readFileSync(join(dir, f)).toString('base64');
    return `  ${JSON.stringify(f.replace(/\.jpg$/, ''))}: "data:image/jpeg;base64,${b64}"`;
  });
  const js =
    '/* generated by _source/build.mjs from the .jpg files beside it. only loaded when the page\n' +
    '   is opened as a file, because browsers will not hand local images to WebGL. */\n' +
    `window.__EARTH_TEXTURES = {\n${parts.join(',\n')}\n};\n`;
  writeFileSync(join(dir, 'textures.js'), js);
  const kb = Math.round(statSync(join(dir, 'textures.js')).size / 1024);
  console.log(`textures.js  ${names.length} images, ${kb} KB`);
}

const jsOptions = {
  ...common,
  entryPoints: [join(here, 'src', 'main.js')],
  outfile: join(assets, 'show.js'),
  format: 'iife',
  minify: true,
  sourcemap: args.includes('--map') ? 'linked' : false, // `node build.mjs --map` for debugging
};

const cssOptions = {
  ...common,
  entryPoints: [join(here, 'css', 'show.css')],
  outfile: join(assets, 'show.css'),
  minify: true,
  loader: { '.woff2': 'dataurl' },
};

// index.html loads each asset with ?v=<hash of its contents>, so a phone that
// cached an older copy is forced to fetch the new one after a redeploy.
function stampIndex() {
  const index = resolve(here, '..', 'index.html');
  let html = readFileSync(index, 'utf8');
  for (const f of ['show.css', 'show.js', 'content.js']) {
    const hash = createHash('sha1').update(readFileSync(join(assets, f))).digest('hex').slice(0, 8);
    html = html.replace(new RegExp(`assets/${f.replace('.', '\\.')}\\?v=[^"']*`), `assets/${f}?v=${hash}`);
  }
  writeFileSync(index, html);
}

if (args.includes('--watch')) {
  const a = await esbuild.context(jsOptions);
  const b = await esbuild.context(cssOptions);
  await Promise.all([a.watch(), b.watch()]);
  writeTextureScript();
  console.log('watching src/ and css/ ...');
} else {
  await Promise.all([esbuild.build(jsOptions), esbuild.build(cssOptions)]);
  for (const f of ['show.js', 'show.css']) {
    console.log(`${f.padEnd(12)} ${Math.round(statSync(join(assets, f)).size / 1024)} KB`);
  }
  writeTextureScript();
  stampIndex();
}
